import {V17_CATEGORIES,V17_SITES} from "../_data/v17-seed.js";
import {json,requireAuth,sameOrigin} from "../_shared/auth.js";

const BACKUP_KEEP=20,MAX_ICON_BYTES=1024*1024;

function normalizeUrl(value){try{const u=new URL(String(value));if(!/^https?:$/.test(u.protocol))return "";u.hash="";u.hostname=u.hostname.toLowerCase();if(u.pathname!=="/")u.pathname=u.pathname.replace(/\/+$/,"");return u.href}catch{return ""}}
function domainOf(value){try{return new URL(value).hostname.toLowerCase().replace(/^www\./,"")}catch{return ""}}
function rootDomain(host){const clean=String(host||"").toLowerCase().replace(/^www\./,"");const p=clean.split(".").filter(Boolean);if(p.length<=2)return clean;const s=p.slice(-2).join("."),special=new Set(["com.cn","net.cn","org.cn","gov.cn","edu.cn","co.uk","com.hk","com.tw","com.au","co.jp","com.sg"]);return special.has(s)&&p.length>=3?p.slice(-3).join("."):p.slice(-2).join(".")}
async function ensureSchema(env){
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS categories_v17(name TEXT PRIMARY KEY,icon TEXT NOT NULL DEFAULT '•',sort_order INTEGER NOT NULL DEFAULT 0,is_builtin INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS sites_v17(id TEXT PRIMARY KEY,name TEXT NOT NULL,url TEXT NOT NULL,normalized_url TEXT NOT NULL UNIQUE,domain TEXT NOT NULL,root_domain TEXT NOT NULL,full_title TEXT,category_name TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,is_favorite INTEGER NOT NULL DEFAULT 0,is_deleted INTEGER NOT NULL DEFAULT 0,is_custom INTEGER NOT NULL DEFAULT 0,icon_url TEXT,icon_key TEXT,visit_count INTEGER NOT NULL DEFAULT 0,last_visited_at TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_sites_v17_category_sort ON sites_v17(category_name,sort_order)`).run();
  await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_sites_v17_root_domain ON sites_v17(root_domain)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS settings_v17(owner TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(owner,key))`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS backups_v17(id INTEGER PRIMARY KEY AUTOINCREMENT,owner TEXT NOT NULL,revision INTEGER NOT NULL,snapshot TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
}
async function getSetting(env,owner,key){const r=await env.DB.prepare(`SELECT value FROM settings_v17 WHERE owner=? AND key=?`).bind(owner,key).first();return r?.value??null}
async function setSetting(env,owner,key,value){await env.DB.prepare(`INSERT INTO settings_v17(owner,key,value,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(owner,key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(owner,key,String(value)).run()}
async function getRevision(env,owner){return Number(await getSetting(env,owner,"revision"))||0}
async function seedIfNeeded(env){const row=await env.DB.prepare(`SELECT COUNT(*) AS c FROM sites_v17`).first();if(Number(row?.c)||0)return false;const catStatements=V17_CATEGORIES.map(c=>env.DB.prepare(`INSERT OR IGNORE INTO categories_v17(name,icon,sort_order,is_builtin) VALUES(?,?,?,1)`).bind(c.name,c.icon,c.sort));await env.DB.batch(catStatements);const siteStatements=V17_SITES.map(s=>{const n=normalizeUrl(s.url),d=domainOf(s.url);return env.DB.prepare(`INSERT OR IGNORE INTO sites_v17(id,name,url,normalized_url,domain,root_domain,full_title,category_name,sort_order,is_custom) VALUES(?,?,?,?,?,?,?,?,?,0)`).bind(s.id,s.name,s.url,n,d,rootDomain(d),s.fullTitle,s.category,s.sort)});for(let i=0;i<siteStatements.length;i+=70)await env.DB.batch(siteStatements.slice(i,i+70));return true}
function dataUrlParts(v){const m=String(v||"").match(/^data:(image\/(?:png|jpeg|jpg|webp|gif|x-icon|vnd\.microsoft\.icon));base64,(.+)$/i);if(!m)return null;try{const raw=atob(m[2]),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return {type:m[1].replace("image/jpg","image/jpeg"),bytes}}catch{return null}}
async function migrateFromV16(env,owner){if(await getSetting(env,owner,"migrated_v16"))return "already";let source="seed-only";try{const old=await env.DB.prepare(`SELECT data FROM nav_state WHERE owner=? LIMIT 1`).bind(owner).first();if(old?.data){const d=JSON.parse(old.data);source="nav_state";
    if(Array.isArray(d.customCategories)){for(let i=0;i<d.customCategories.length;i++){const c=d.customCategories[i];if(c?.name)await env.DB.prepare(`INSERT OR IGNORE INTO categories_v17(name,icon,sort_order,is_builtin) VALUES(?,?,?,0)`).bind(String(c.name),String(c.icon||"•"),100+i).run()}}
    if(Array.isArray(d.custom)){for(const s of d.custom){const n=normalizeUrl(s?.url);if(!n)continue;const domain=domainOf(n),cat=String(d.categoryOverrides?.[s.id]||s.category||V17_CATEGORIES[0].name);try{await env.DB.prepare(`INSERT OR IGNORE INTO sites_v17(id,name,url,normalized_url,domain,root_domain,full_title,category_name,sort_order,is_custom,icon_url) VALUES(?,?,?,?,?,?,?,?,?,1,?)`).bind(String(s.id),String(s.name||domain),n,n,domain,rootDomain(domain),String(s.fullTitle||s.name||domain),cat,999,String(s.iconUrl||"")).run()}catch{}}}
    if(d.siteEdits&&typeof d.siteEdits==="object"){for(const [id,e] of Object.entries(d.siteEdits)){const n=normalizeUrl(e?.url);if(!n)continue;const domain=domainOf(n);await env.DB.prepare(`UPDATE sites_v17 SET name=?,url=?,normalized_url=?,domain=?,root_domain=?,full_title=?,icon_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(String(e?.name||domain),n,n,domain,rootDomain(domain),String(e?.name||domain),String(e?.iconUrl||""),id).run()}}
    if(d.categoryOverrides&&typeof d.categoryOverrides==="object"){for(const [id,cat] of Object.entries(d.categoryOverrides))await env.DB.prepare(`UPDATE sites_v17 SET category_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(String(cat),id).run()}
    if(Array.isArray(d.favorites)){for(const id of d.favorites)await env.DB.prepare(`UPDATE sites_v17 SET is_favorite=1 WHERE id=?`).bind(String(id)).run()}
    if(Array.isArray(d.hiddenSites)){for(const id of d.hiddenSites)await env.DB.prepare(`UPDATE sites_v17 SET is_deleted=1 WHERE id=?`).bind(String(id)).run()}
    if(Array.isArray(d.categoryOrder)){for(let i=0;i<d.categoryOrder.length;i++)await env.DB.prepare(`UPDATE categories_v17 SET sort_order=? WHERE name=?`).bind(i,String(d.categoryOrder[i])).run()}
    if(d.categoryIconOverrides&&typeof d.categoryIconOverrides==="object"){for(const [name,icon] of Object.entries(d.categoryIconOverrides))await env.DB.prepare(`UPDATE categories_v17 SET icon=? WHERE name=?`).bind(String(icon||"•"),String(name)).run()}
    if(d.siteOrder&&typeof d.siteOrder==="object"){for(const [cat,ids] of Object.entries(d.siteOrder)){if(!Array.isArray(ids))continue;for(let i=0;i<ids.length;i++)await env.DB.prepare(`UPDATE sites_v17 SET sort_order=?,category_name=? WHERE id=?`).bind(i,String(cat),String(ids[i])).run()}}
    const ui={recents:Array.isArray(d.recents)?d.recents:[],usageStats:d.usageStats&&typeof d.usageStats==="object"?d.usageStats:{},density:d.density||"comfortable",theme:d.theme||"dark"};await setSetting(env,owner,"ui",JSON.stringify(ui));
    if(env.KV&&d.iconOverrides&&typeof d.iconOverrides==="object"){for(const [id,val] of Object.entries(d.iconOverrides)){const p=dataUrlParts(val);if(!p||p.bytes.byteLength>MAX_ICON_BYTES)continue;const key=`custom:${owner}:${id}:${crypto.randomUUID()}`;await env.KV.put(key,p.bytes,{metadata:{contentType:p.type,kind:"custom"}});await env.DB.prepare(`UPDATE sites_v17 SET icon_key=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(key,id).run()}}
  }}catch{}
  await setSetting(env,owner,"migrated_v16","1");return source
}
async function buildBootstrap(env,owner,migrationSource){const cats=(await env.DB.prepare(`SELECT * FROM categories_v17 ORDER BY sort_order,name`).all()).results||[];const sites=(await env.DB.prepare(`SELECT * FROM sites_v17 ORDER BY category_name,sort_order,name`).all()).results||[];let settings={};try{settings=JSON.parse(await getSetting(env,owner,"ui")||"{}")||{}}catch{}return {ok:true,revision:await getRevision(env,owner),migrationSource,categories:cats,sites,settings,iconStore:"kv",kv:!!env.KV}}
async function backupSnapshot(env,owner,revision){const snap=await buildBootstrap(env,owner,"backup");await env.DB.prepare(`INSERT INTO backups_v17(owner,revision,snapshot,created_at) VALUES(?,?,?,CURRENT_TIMESTAMP)`).bind(owner,revision,JSON.stringify(snap)).run();await env.DB.prepare(`DELETE FROM backups_v17 WHERE owner=? AND id NOT IN (SELECT id FROM backups_v17 WHERE owner=? ORDER BY id DESC LIMIT ?)`).bind(owner,owner,BACKUP_KEEP).run()}
function validateSnapshot(body){const cats=Array.isArray(body?.categories)?body.categories:[],sites=Array.isArray(body?.sites)?body.sites:[];const seen=new Map(),dups=[];for(const s of sites){const n=normalizeUrl(s?.url);if(!n)continue;if(seen.has(n))dups.push({url:n,a:seen.get(n),b:s.id});else seen.set(n,s.id)}return {cats,sites,dups}}
async function syncSnapshot(env,owner,body){const {cats,sites,dups}=validateSnapshot(body);if(dups.length)return json({ok:false,error:"Duplicate URL detected.",duplicates:dups},409);const current=await getRevision(env,owner),base=Math.max(0,Number(body?.baseRevision)||0),force=body?.force===true;if(!force&&base!==current)return json({ok:false,error:"Revision conflict.",revision:current},409);await backupSnapshot(env,owner,current);
  const existing=(await env.DB.prepare(`SELECT id,is_custom,icon_key FROM sites_v17`).all()).results||[],incoming=new Set(sites.map(s=>String(s.id)));for(const r of existing){if(Number(r.is_custom)!==0&&!incoming.has(String(r.id))){if(env.KV&&r.icon_key&&String(r.icon_key).startsWith("custom:"))await env.KV.delete(r.icon_key);await env.DB.prepare(`DELETE FROM sites_v17 WHERE id=?`).bind(r.id).run()}}
  for(const c of cats){const name=String(c?.name||"").trim();if(!name)continue;await env.DB.prepare(`INSERT INTO categories_v17(name,icon,sort_order,is_builtin,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(name) DO UPDATE SET icon=excluded.icon,sort_order=excluded.sort_order,is_builtin=excluded.is_builtin,updated_at=CURRENT_TIMESTAMP`).bind(name,String(c.icon||"•"),Number(c.sortOrder)||0,c.isBuiltin?1:0).run()}
  const catNames=new Set(cats.map(c=>String(c.name)));const dbCats=(await env.DB.prepare(`SELECT name,is_builtin FROM categories_v17`).all()).results||[];for(const c of dbCats)if(Number(c.is_builtin)===0&&!catNames.has(String(c.name)))await env.DB.prepare(`DELETE FROM categories_v17 WHERE name=?`).bind(c.name).run();
  for(const s of sites){const id=String(s.id||"").trim(),n=normalizeUrl(s.url);if(!id||!n)continue;const d=domainOf(n),cat=String(s.category||V17_CATEGORIES[0].name),iconUrl=String(s.iconUrl||"");await env.DB.prepare(`INSERT INTO sites_v17(id,name,url,normalized_url,domain,root_domain,full_title,category_name,sort_order,is_favorite,is_deleted,is_custom,icon_url,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET name=excluded.name,url=excluded.url,normalized_url=excluded.normalized_url,domain=excluded.domain,root_domain=excluded.root_domain,full_title=excluded.full_title,category_name=excluded.category_name,sort_order=excluded.sort_order,is_favorite=excluded.is_favorite,is_deleted=excluded.is_deleted,is_custom=excluded.is_custom,icon_url=excluded.icon_url,updated_at=CURRENT_TIMESTAMP`).bind(id,String(s.name||d),n,n,d,rootDomain(d),String(s.fullTitle||s.name||d),cat,Number(s.sortOrder)||0,s.isFavorite?1:0,s.isDeleted?1:0,s.isCustom?1:0,iconUrl).run()}
  const ui=body?.settings&&typeof body.settings==="object"?body.settings:{};await setSetting(env,owner,"ui",JSON.stringify(ui));const revision=current+1;await setSetting(env,owner,"revision",String(revision));return json({ok:true,revision})
}
function kvIconResponse(value,metadata={}){const type=metadata?.contentType||"image/png";return new Response(value,{headers:{"Content-Type":type,"Cache-Control":"private, max-age=86400, stale-while-revalidate=604800","X-Content-Type-Options":"nosniff"}})}
function fallbackSvg(name){const ch=String(name||"?").trim().charAt(0).toUpperCase()||"?";return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#7187ff"/><stop offset="1" stop-color="#a45cf6"/></linearGradient></defs><rect width="128" height="128" rx="28" fill="url(#g)"/><text x="64" y="80" text-anchor="middle" font-family="Arial,sans-serif" font-size="64" font-weight="700" fill="white">${ch.replace(/[<>&]/g,"")}</text></svg>`}
async function fetchCandidate(url){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),3500);try{const r=await fetch(url,{redirect:"follow",signal:ctl.signal,headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)return null;const ct=(r.headers.get("content-type")||"").split(";")[0].trim();if(!ct.startsWith("image/"))return null;const buf=await r.arrayBuffer();if(buf.byteLength<350||buf.byteLength>MAX_ICON_BYTES)return null;return {buf,type:ct}}catch{return null}finally{clearTimeout(t)}}
async function getKvIcon(env,key){if(!env.KV)return null;const got=await env.KV.getWithMetadata(key,{type:"arrayBuffer",cacheTtl:86400});if(!got?.value)return null;return {value:got.value,metadata:got.metadata||{}}}
async function serveIcon(env,site){if(!env.KV)return new Response(fallbackSvg(site.name),{headers:{"Content-Type":"image/svg+xml; charset=utf-8","Cache-Control":"no-store"}});if(site.icon_key){const custom=await getKvIcon(env,site.icon_key);if(custom)return kvIconResponse(custom.value,custom.metadata)}const root=site.root_domain||rootDomain(site.domain),key=`favicon:${root}`,cached=await getKvIcon(env,key);if(cached)return kvIconResponse(cached.value,cached.metadata);const sources=[];if(site.icon_url&&/^https?:\/\//i.test(site.icon_url))sources.push(site.icon_url);sources.push(`https://www.google.com/s2/favicons?sz=256&domain_url=${encodeURIComponent(site.url)}`,`https://icon.horse/icon/${encodeURIComponent(site.domain)}`,`https://icons.duckduckgo.com/ip3/${encodeURIComponent(site.domain)}.ico`);for(const u of sources){const got=await fetchCandidate(u);if(!got)continue;await env.KV.put(key,got.buf,{expirationTtl:60*60*24*30,metadata:{contentType:got.type,kind:"favicon",source:u,domain:site.domain}});return kvIconResponse(got.buf,{contentType:got.type})}return new Response(fallbackSvg(site.name),{headers:{"Content-Type":"image/svg+xml; charset=utf-8","Cache-Control":"private, max-age=3600"}})}

export async function onRequest(context){const {request,env}=context;try{await ensureSchema(env);const auth=await requireAuth(request,env);if(auth.error)return auth.error;const url=new URL(request.url),mode=String(url.searchParams.get("mode")||"");
  if(mode==="bootstrap"&&request.method==="GET"){const seeded=await seedIfNeeded(env),source=await migrateFromV16(env,auth.owner);if(seeded&&!await getSetting(env,auth.owner,"revision"))await setSetting(env,auth.owner,"revision","1");return json(await buildBootstrap(env,auth.owner,source))}
  if(mode==="sync"&&request.method==="POST"){if(!sameOrigin(request))return json({ok:false,error:"Invalid origin."},403);return await syncSnapshot(env,auth.owner,await request.json())}
  if(mode==="icon"&&request.method==="GET"){const id=String(url.searchParams.get("site")||"");const site=await env.DB.prepare(`SELECT * FROM sites_v17 WHERE id=? LIMIT 1`).bind(id).first();if(!site)return json({ok:false,error:"Site not found."},404);return await serveIcon(env,site)}
  if(mode==="upload-icon"&&request.method==="POST"){if(!sameOrigin(request))return json({ok:false,error:"Invalid origin."},403);if(!env.KV)return json({ok:false,error:"Missing KV binding: KV"},500);const id=String(url.searchParams.get("site")||""),site=await env.DB.prepare(`SELECT id,icon_key FROM sites_v17 WHERE id=? LIMIT 1`).bind(id).first();if(!site)return json({ok:false,error:"Site not found."},404);const type=(request.headers.get("content-type")||"").split(";")[0].trim().toLowerCase(),allowed=new Set(["image/png","image/jpeg","image/webp","image/gif","image/x-icon","image/vnd.microsoft.icon"]);if(!allowed.has(type))return json({ok:false,error:"Only PNG/JPG/WebP/GIF/ICO are allowed."},415);const buf=await request.arrayBuffer();if(!buf.byteLength||buf.byteLength>MAX_ICON_BYTES)return json({ok:false,error:"Icon must be 1MB or smaller."},413);const key=`custom:${auth.owner}:${id}:${crypto.randomUUID()}`;await env.KV.put(key,buf,{metadata:{contentType:type,kind:"custom"}});if(site.icon_key&&String(site.icon_key).startsWith("custom:"))await env.KV.delete(site.icon_key);await env.DB.prepare(`UPDATE sites_v17 SET icon_key=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(key,id).run();const rev=await getRevision(env,auth.owner)+1;await setSetting(env,auth.owner,"revision",String(rev));return json({ok:true,revision:rev})}
  if(mode==="reset-icon"&&request.method==="POST"){if(!sameOrigin(request))return json({ok:false,error:"Invalid origin."},403);const id=String(url.searchParams.get("site")||""),site=await env.DB.prepare(`SELECT icon_key FROM sites_v17 WHERE id=? LIMIT 1`).bind(id).first();if(!site)return json({ok:false,error:"Site not found."},404);if(env.KV&&site.icon_key&&String(site.icon_key).startsWith("custom:"))await env.KV.delete(site.icon_key);await env.DB.prepare(`UPDATE sites_v17 SET icon_key=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();const rev=await getRevision(env,auth.owner)+1;await setSetting(env,auth.owner,"revision",String(rev));return json({ok:true,revision:rev})}
  return json({ok:false,error:"Not found."},404)
}catch(e){return json({ok:false,error:"V17 API error: "+String(e?.message||e)},500)}}
