const enc=new TextEncoder(),dec=new TextDecoder();
export function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff",...headers}})}
function getCookie(request,name){const raw=request.headers.get("Cookie")||"";for(const part of raw.split(";")){const [k,...rest]=part.trim().split("=");if(k===name)return rest.join("=")}return ""}
function b64d(value){const padded=value.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((value.length+3)%4);const raw=atob(padded);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function ct(a,b){if(!(a instanceof Uint8Array)||!(b instanceof Uint8Array))return false;let d=a.length^b.length,len=Math.max(a.length,b.length);for(let i=0;i<len;i++)d|=(a[i%a.length]||0)^(b[i%b.length]||0);return d===0}
async function hmac(secret,text){const key=await crypto.subtle.importKey("raw",enc.encode(String(secret)),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(text)))}
export function normalizeUsername(v){return String(v||"").trim().toLowerCase()}
export async function verifySession(request,env){const token=getCookie(request,"fxnav_session");if(!token||!token.includes("."))return null;const [p,s]=token.split(".",2);try{const expected=await hmac(env.SESSION_SECRET,p),actual=b64d(s);if(!ct(expected,actual))return null;const payload=JSON.parse(dec.decode(b64d(p))),now=Math.floor(Date.now()/1000);if(!payload||payload.exp<now||payload.iat>now+60)return null;if(normalizeUsername(payload.u)!==normalizeUsername(env.NAV_USERNAME))return null;return payload}catch{return null}}
export async function requireAuth(request,env){if(!env.DB||!env.NAV_USERNAME||!env.SESSION_SECRET)return {error:json({ok:false,error:"Server bindings are not configured."},500)};const session=await verifySession(request,env);if(!session)return {error:json({ok:false,error:"Authentication required."},401)};return {owner:normalizeUsername(env.NAV_USERNAME),session}}
export function sameOrigin(request){const origin=request.headers.get("Origin");if(!origin)return false;try{return new URL(origin).host===new URL(request.url).host}catch{return false}}
